<a href="https://colab.research.google.com/github/Sayak-Rana/Data_Science/blob/main/1_Numpy_appliedai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Check speeds of Normal Array vs Numpy Array

In [ ]:
# Python Lists
L = range(1000)
%timeit [i**2 for i in L]

# Numpy Array
a = np.arange(1000)
%timeit [i**2 for i in a] # Traverse Numpy arrays and doing calc
# Non -vectorized operation (slowest)
# Actually using Numpy arrays

%timeit a**2 #Vectorized operations fastest

# Shows how Numpy array is much faster

68.8 µs ± 5.49 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
175 µs ± 98.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
2.54 µs ± 276 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Create Numpy array methods

In [12]:
# Method-1
arr1 = np.array([3,4,5,6,7])
print(arr1)

[3 4 5 6 7]


In [14]:
# Method-2
arr2 = np.arange(10) # This basically creates a list starting from 0 to 9
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
# Method-3
arr3 = np.arange(10,20) # This basically creates a list starting from 10 to 19
print(arr3)

[10 11 12 13 14 15 16 17 18 19]


In [16]:
# Method-4
arr4 = np.arange(10,20,2) # This basically creates a list starting from 10 to 19 with a step of 2
print(arr4)

[10 12 14 16 18]


In [17]:
# Method-5
arr5 = np.linspace(10,20,5) # This basically creates a list starting from 10 to 20 with 5 elements
# maintaining a uniform spacing between all
print(arr5)

[10.  12.5 15.  17.5 20. ]


In [18]:
# for n-dim arrays function arguments need to be (tuples)
# Method-6
arr6 = np.empty(3) # Creates 1D array with three random numbers.
print(arr6)

[0.  0.5 1. ]


In [19]:
# Method-7
arr7 = np.empty((2,3)) # Creates 2D array with random numbers (Garbage values)
print(arr7)

[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# Method-8
arr8 = np.zeros((3,2)) # 2D rray with all zeroes
print(arr8)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [21]:
# Method-9
arr9 = np.ones((3,2)) # 2D rray with all zeroes
print(arr9)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
# Method-10
arr10 = np.eye(3) # 3*3 Identity Matrix
print(arr10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
# Method-11
# arr11 = np.eye((3,2)) # Here it is wrong as eye don't expect tuples
arr11 = np.eye(3,2) # Correct, 3 is no of rows , 2 is no of columns
print(arr11)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [28]:
# Method-12
arr12 = np.diag([1,2,3,4])
print(arr12) #creates a matric with these diagonal elements
L= np.diag(arr12) #returns the diagonal as list
for i in range(len(L)):
  print(L[i],end=" ")
np.trace(arr12) #returns the sum of diagonal elements

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
1 2 3 4 

np.int64(10)

In [30]:
# Creating Random numbers

# arr13 = np.random.rand((2,3)) # wrong no tuple expected
arr13 = np.random.rand(2,3) # Correct
print(arr13) # Follows Uniform Dist

[[0.12336914 0.83743724 0.391135  ]
 [0.79454826 0.36312829 0.37193921]]


In [31]:
arr14 = np.random.randn(2,3) # Correct
print(arr14) # Follows Standard Normal Dist

[[-1.24472762  1.41842628 -0.84438451]
 [ 0.05826264  0.92690525 -0.72116298]]


Create 2D array

In [ ]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

print(len(arr2d)) # Prints no. of rows

print(arr2d.ndim) # Prints the dimension which is 2

print(arr2d.shape) #Prints the shape of the matrix like 3*3

print(arr2d.size) # Prints the total no. of elements

print(arr2d.dtype) # Prints the data type

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
2
(3, 3)
9
int64


Create a 3D array

In [9]:
# arr3d = np.array([[1,2],[3,4]],[[6,7,8],[9,10]]) # this can't be done like [6,7,8] consists of 3 elements
# arr3d = np.array([[[1,2],[3,4]],[[6,7],[8,9],[10,11]]]) # Wrong as arr3d[1] no of elements is actually 3 it must be uniform so 2.
arr3d = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]]) # Correct
print(arr3d)

print(len(arr3d)) # Prints length of arr3d

print(arr3d[0].size) # prints total no of elements

print(arr3d.ndim) # Prints the dimension which is 3

print(arr3d.shape) #Prints the shape of the matrix like 2*(2*3) => () is each individual 2*3 matrix and there are 2 such

print(arr3d[1].shape)

[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]
2
6
3
(2, 2, 3)
(2, 3)


Basic Data types

In [34]:
a = np.arange(10)
print(a.dtype)

b = np.arange(10,dtype="float64")
print(b.dtype) # Changes dtype to float

c = np.zeros((3,3))
print(c.dtype) # By default these support float dtype
# same goes for np.ones

d = np.array([1+2j, 3+4j])
print(d.dtype)

e = np.array(['Ram', 'Robert', 'Rahim'])
print(e.dtype)

f = np.array([True, False])
print(f.dtype)

int64
float64
float64
complex128
<U6
bool


Indexing and Slicing

In [47]:
a = np.arange(10,20)
print(a)
print(a[2]) # third element

b = np.diag([1,2,3])
print(b)
b[2,1] = 5 # 3rd row, 2nd col
print(b)
print(b[2][2])
print(b[2,2]) # these two indexing are identical indicates 3rd row, 3rd col

[10 11 12 13 14 15 16 17 18 19]
12
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1 0 0]
 [0 2 0]
 [0 5 3]]
3
3


In [50]:
# Knowledge
# Create 2D array with random numbers in python without numpy
import random

c = []
for i in range(3):
  temp = []
  for j in range(4):
    temp.append(random.randint(1,10))
  c.append(temp)
print(c)

# 3D array
c = []
for i in range(2):
  temp1 = []
  for j in range(3):
    temp2 = []
    for k in range(4):
      temp2.append(random.randint(1,10))
    temp1.append(temp2)
  c.append(temp1)
print(c)

# Using List comprehension
c = [[[random.randint(1,10) for k in range(4)]for j in range(3)]for i in range(2)]
print(c)
# You could have used random.random() or random.uniform(a,b)

# Convert list to NumPy array to access the shape attribute
c_np = np.array(c)
print(c_np.shape)

[[6, 8, 10, 2], [4, 2, 6, 2], [7, 8, 3, 1]]
[[[4, 4, 1, 9], [3, 4, 4, 7], [8, 7, 8, 1]], [[8, 7, 3, 8], [9, 9, 2, 1], [7, 7, 3, 1]]]
[[[10, 7, 4, 8], [3, 2, 5, 1], [2, 7, 3, 4]], [[6, 9, 9, 5], [9, 10, 3, 6], [7, 7, 9, 8]]]
(2, 3, 4)


In [62]:
# slicing (Normal Python slicing)
a = np.arange(10)
print(a)
print(a[1:9:2]) # [start:end+1:step]

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


In [64]:
b = np.arange(3)
print(b)
a[8:] = b[::-1][:2] #first reversing and then taking first two
print(a)

[0 1 2]
[0 1 2 3 4 5 6 7 2 1]


Creating Views

In [65]:
a = np.arange(10)
print(a)

b = a[::2]
print(b)

print(np.shares_memory(a,b))
# True indicates that they point to same memory location
# So changes in b will also change a

b[0] = 10
print(b)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
True
[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [67]:
# Avoid this using clone or copy function
c = a[::2].copy()
# In Pytorch .clone() method exists

print(c)
print(np.shares_memory(a,c))

c[0] = 12
print(c)
print(a)

[10  2  4  6  8]
False
[12  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


Fancy Indexing (Mask)

In [72]:
a = np.random.randint(10,30,15) # (start, end+1, no of numbers)
print(a)
mask = (a % 2 == 0)
extract_a = a[mask]
print(extract_a)
# Mask Creates copies not views

a[mask] = -1 #replace all even numbers with -1
print(a)

[21 15 18 28 23 20 27 26 26 23 27 20 20 27 20]
[18 28 20 26 26 20 20 20]
[21 15 -1 -1 23 -1 27 -1 -1 23 27 -1 -1 27 -1]


In [78]:
print(a)
b = a[[2,10,2,4]] # b is list consisting of a's 2,310,2,4 indexes
print(b)

a[[2,3]] = -1000
print(a) # We can also assign in this way

[21 15 -1 -1 23 -1 27 -1 -1 23 27 -1 -1 27 -1]
[-1 27 -1 23]
[   21    15 -1000 -1000    23    -1    27    -1    -1    23    27    -1
    -1    27    -1]
